
[package]
name = "bucceolang"
version = "0.1.0"
authors = ["Lukas Weger<mail@weger.dev>"]
edition = "2021"

[dependencies]
reqwest = { version = "0.12.19", features = ["blocking"] }
wasm-bindgen = "0.2.100"

[lib]
crate-type = ["cdylib", "rlib"]
